[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

[features]
default = ["section04"]
# default = ["section01", "section02", "section03", "section04"]
section01 = []
section02 = []
section03 = []
section04 = []

[dependencies]
rand = "0.8.5"
