name: Push or PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_n_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: rustfmt
      run: cargo fmt --all -- --check
    - name: check
      run: cargo check --verbose
    - name: clippy
      run: cargo clippy --all-targets --all-features
    - name: Build
      run: cargo build --verbose --examples --tests --all-features
    - name: Test
      run: cargo test --verbose --all-features
